"""Research kernel: structured single-agent research loop and its contracts."""

from research_explorer.research.agent import (
    AgentOutputError,
    LLMReferenceMapper,
    LLMResearchAgent,
    ReferenceMapper,
    ReferenceMappingError,
    ResearchAgent,
    parse_agent_brief,
    reference_schema,
)
from research_explorer.research.answer import build_final_answer
from research_explorer.research.context import (
    build_agent_prompt,
    build_evaluation_prompt,
    rubric_schema,
)
from research_explorer.research.evaluator import (
    CompositeEvaluator,
    DeterministicIntegrity,
    LLMRubricEvaluator,
    parse_claim_verdicts,
)
from research_explorer.research.loop import (
    Acquisition,
    EvidenceGateway,
    GraphEvidenceGateway,
    KernelOptions,
    ResearchKernel,
    SearchOutcome,
)
from research_explorer.research.models import (
    ActionKind,
    AgentBrief,
    AgentNotebook,
    BudgetState,
    CandidateAction,
    Claim,
    ClaimMutation,
    ClaimStatus,
    ClaimVerdict,
    EvidenceRef,
    FinalAnswer,
    OpenQuestion,
    OpenQuestionStatus,
    ProviderOutcome,
    ResearchAction,
    ResearchEvaluation,
    ResearchEvent,
    ResearchObjective,
    ResearchState,
    SlotState,
    VerdictAssessment,
    normalize_query,
)
from research_explorer.research.policy import ExplorationPolicy, GreedyPolicy
from research_explorer.research.store import ResearchStore

__all__ = [
    "Acquisition",
    "ActionKind",
    "AgentBrief",
    "AgentNotebook",
    "AgentOutputError",
    "BudgetState",
    "CandidateAction",
    "Claim",
    "ClaimMutation",
    "ClaimStatus",
    "ClaimVerdict",
    "CompositeEvaluator",
    "DeterministicIntegrity",
    "EvidenceGateway",
    "EvidenceRef",
    "ExplorationPolicy",
    "FinalAnswer",
    "GraphEvidenceGateway",
    "GreedyPolicy",
    "KernelOptions",
    "LLMReferenceMapper",
    "LLMResearchAgent",
    "LLMRubricEvaluator",
    "OpenQuestion",
    "OpenQuestionStatus",
    "ProviderOutcome",
    "ReferenceMapper",
    "ReferenceMappingError",
    "ResearchAction",
    "ResearchAgent",
    "ResearchEvaluation",
    "ResearchEvent",
    "ResearchKernel",
    "ResearchObjective",
    "ResearchState",
    "ResearchStore",
    "SearchOutcome",
    "SlotState",
    "VerdictAssessment",
    "build_agent_prompt",
    "build_evaluation_prompt",
    "build_final_answer",
    "normalize_query",
    "parse_agent_brief",
    "parse_claim_verdicts",
    "reference_schema",
    "rubric_schema",
]
