"""Hidden examination and matched naive baseline (EXAM-1..9)."""

from research_explorer.examination.benchmark import (
    OUTCOME_BENCHMARKED,
    OUTCOME_DEGRADED,
    OUTCOME_FAILED,
    OUTCOME_SURVIVOR_UNBENCHMARKED,
    REASON_BASELINE_FAILED,
    REASON_EXAMINER_UNAVAILABLE,
    REASON_INSUFFICIENT_QUESTIONS,
    REASON_INVALID_CANDIDATE_RESPONSE,
    REASON_NO_ELIGIBLE_SURVIVOR,
    BenchmarkConfig,
    BenchmarkRunner,
    config_fingerprint,
)
from research_explorer.examination.clients import (
    AnswerClient,
    FakeAnswerClient,
    LLMAnswerClient,
    build_answer_set,
)
from research_explorer.examination.generator import (
    EvidenceInsufficientError,
    ExamGenerator,
    FakeExaminer,
    GenerationSpec,
    LLMExaminer,
    build_answer_key,
)
from research_explorer.examination.models import (
    CATEGORY_DISTRIBUTION,
    EXAM_SCHEMA_VERSION,
    STATUS_REJECTED,
    STATUS_VALIDATED,
    AnswerKey,
    AnswerRecord,
    AnswerSet,
    BenchmarkResult,
    CandidateMemory,
    CategoryScore,
    EvidenceEntry,
    EvidencePack,
    ExamBank,
    ExamItem,
    ExamOption,
    ExamScore,
    SelectionWeights,
    SourceExclusion,
    StudentQuestion,
    SurvivorSelection,
)
from research_explorer.examination.pack import build_evidence_pack, evidence_entry_from_dossier
from research_explorer.examination.partition import PartitionError, partition_bank
from research_explorer.examination.report import (
    benchmark_report_markdown,
    benchmark_result_json,
    private_key_artifact,
    public_exam_artifact,
)
from research_explorer.examination.scoring import paired_outcomes, score_answers
from research_explorer.examination.selection import (
    candidate_eligibility,
    grounding_score,
    select_survivor,
)
from research_explorer.examination.synthetic import (
    build_synthetic_corpus,
    build_synthetic_dossiers,
)
from research_explorer.examination.validation import validate_bank, validate_item

__all__ = [
    "CATEGORY_DISTRIBUTION",
    "EXAM_SCHEMA_VERSION",
    "OUTCOME_BENCHMARKED",
    "OUTCOME_DEGRADED",
    "OUTCOME_FAILED",
    "OUTCOME_SURVIVOR_UNBENCHMARKED",
    "REASON_BASELINE_FAILED",
    "REASON_EXAMINER_UNAVAILABLE",
    "REASON_INSUFFICIENT_QUESTIONS",
    "REASON_INVALID_CANDIDATE_RESPONSE",
    "REASON_NO_ELIGIBLE_SURVIVOR",
    "STATUS_REJECTED",
    "STATUS_VALIDATED",
    "AnswerClient",
    "AnswerKey",
    "AnswerRecord",
    "AnswerSet",
    "BenchmarkConfig",
    "BenchmarkResult",
    "BenchmarkRunner",
    "CandidateMemory",
    "CategoryScore",
    "EvidenceEntry",
    "EvidenceInsufficientError",
    "EvidencePack",
    "ExamBank",
    "ExamGenerator",
    "ExamItem",
    "ExamOption",
    "ExamScore",
    "FakeAnswerClient",
    "FakeExaminer",
    "GenerationSpec",
    "LLMAnswerClient",
    "LLMExaminer",
    "PartitionError",
    "SelectionWeights",
    "SourceExclusion",
    "StudentQuestion",
    "SurvivorSelection",
    "benchmark_report_markdown",
    "benchmark_result_json",
    "build_answer_key",
    "build_answer_set",
    "build_evidence_pack",
    "build_synthetic_corpus",
    "build_synthetic_dossiers",
    "candidate_eligibility",
    "config_fingerprint",
    "evidence_entry_from_dossier",
    "grounding_score",
    "paired_outcomes",
    "partition_bank",
    "private_key_artifact",
    "public_exam_artifact",
    "score_answers",
    "select_survivor",
    "validate_bank",
    "validate_item",
]
